make:
	gcc -o question_03a question_03a.c
	gcc -o question_4 question_4.c
req:
	sudo apt update
	sudo apt-get install jq -y
permission:
	chmod +x question_03a.c
	chmod +x question_4.c
	chmod +x question_01.sh
	chmod +x question_02.sh
