
make:
	gcc -o  question_03  question_03.c
	gcc -o  question_04  question_04.c
	gcc -o  question_05  question_05.c

permission:
	chmod +x  question_03.c
	chmod +x  question_04.c
	chmod +x  question_05.c
